databases:
  - name: assign
    databaseName: assign
    user: assign_user

services:
  - type: web
    name: assign
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn carefi_assign.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: assign
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
